apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: theo18/mon-api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: api-config

## Deux parties dont une avec le Rolling update et les probes (ci-dessous) (laisser en commantaire car erreur persistantes non r√©solues)


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api-deployment
# spec:
#   replicas: 3
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 0
#   selector:
#     matchLabels:
#       app: api
#   template:
#     metadata:
#       labels:
#         app: api
#     spec:
#       containers:
#       - name: api
#         image: theo18/mon-api:latest
#         ports:
#         - containerPort: 3000
#         envFrom:
#         - configMapRef:
#             name: api-config
#         resources:
#           requests:
#             cpu: "100m"
#             memory: "128Mi"
#           limits:
#             cpu: "500m"
#             memory: "256Mi"
#         livenessProbe:
#           httpGet:
#             path: /health
#             port: 3000
#           initialDelaySeconds: 10
#           periodSeconds: 15
#         readinessProbe:
#           httpGet:
#             path: /health
#             port: 3000
#           initialDelaySeconds: 5
#           periodSeconds: 10